# Generated by Django 3.0 on 2020-05-31 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=200)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense.CreditCard')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expense.TransactionImport'),
        ),
    ]
